Repository wix/stylable, pull requests merged in 2018-07, with the labels that each got.

#374 webpack-plugin: Add a sample project using postcss autoprefixer plugin
  package.json
  packages/stylable-webpack-plugin/test/e2e/autoprefixer-project.spec.ts
  packages/stylable-webpack-plugin/test/e2e/projects/autoprefixer-project/src/index.js
  packages/stylable-webpack-plugin/test/e2e/projects/autoprefixer-project/src/index.st.css
  packages/stylable-webpack-plugin/test/e2e/projects/autoprefixer-project/webpack.config.js
  yarn.lock
Labels: integration, question

#380 Centralize scripts global types usage
  packages/stylable-jest/test/jest.spec.ts
  packages/stylable-node/src/stylable-module-source.ts
  packages/stylable-node/test/require-hook.spec.ts
  packages/stylable-scripts/template/src/globals.d.ts
Labels: core, integration

#382 Report error when defining states beginning with "--"
  packages/stylable/src/pseudo-states.ts
  packages/stylable/tests/pseudo-states.spec.ts
Labels: core, diagnostics, pseudo-state

#384 Core: remove deprecated features
  packages/stylable-webpack-plugin/test/e2e/dev-mode-warnings-project.spec.ts
  packages/stylable/README.md
  packages/stylable/src/bundle.ts
  packages/stylable/src/index.ts
  packages/stylable/src/selector-utils.ts
  packages/stylable/src/stylable-meta.ts
  packages/stylable/src/stylable-processor.ts
  packages/stylable/src/stylable-transformer.ts
  packages/stylable/src/stylable-value-parsers.ts
  packages/stylable/src/stylable.ts
  packages/stylable/tests/bundle/base.spec.ts
  packages/stylable/tests/bundle/theme.spec.ts
  packages/stylable/tests/diagnostics.spec.ts
  packages/stylable/tests/stylable-processor.spec.ts
  packages/stylable/tests/stylable-transformer/compose.spec.ts
  packages/stylable/tests/stylable-transformer/scoping.spec.ts
  packages/stylable/tests/stylable-transformer/theme.spec.ts
  packages/stylable/tests/utils/generate-test-util.ts
Labels: core, tech debt

#388 fix builder output
  packages/stylable-webpack-extensions/src/component-metadata-builder.ts
  packages/stylable-webpack-extensions/src/index.ts
Labels: integration

#387 Core: remove root scoping
  packages/stylable-webpack-plugin/README.md
  packages/stylable-webpack-plugin/src/PluginOptions.js
  packages/stylable-webpack-plugin/src/StylableWebpackPlugin.js
  packages/stylable-webpack-plugin/test/e2e/projects/autoprefixer-project/webpack.config.js
  packages/stylable-webpack-plugin/test/e2e/projects/optimizations/webpack.config.js
  packages/stylable/src/stylable-mixins.ts
  packages/stylable/src/stylable-transformer.ts
  packages/stylable/src/stylable.ts
  packages/stylable/tests/mixins/css-mixins.spec.ts
  packages/stylable/tests/mixins/js-mixins.spec.ts
  packages/stylable/tests/stylable-transformer/global.spec.ts
  packages/stylable/tests/stylable-transformer/optimize.spec.ts
  packages/stylable/tests/stylable-transformer/post-process-and-hooks.spec.ts
  packages/stylable/tests/utils/generate-test-util.ts
Labels: core, tech debt

#386 Core: fix dev-mode windows test
  packages/stylable/src/stylable-transformer.ts
Labels: bug, core, diagnostics, tests
