Repository wix/stylable, pull requests merged in 2018-08, with the labels that each got.

#396 Add README files to all packages
  .gitignore
  README.md
  packages/e2e-test-kit/LICENSE
  packages/e2e-test-kit/README.md
  packages/e2e-test-kit/package.json
  packages/e2e-test-kit/src/index.ts
  packages/e2e-test-kit/src/mem-fs.ts
  packages/e2e-test-kit/src/project-runner.ts
  packages/e2e-test-kit/src/puppeteer-helpers.ts
  packages/e2e-test-kit/src/stylable-project-runner.ts
  packages/e2e-test-kit/src/stylable-webpack-test-utils.ts
  packages/e2e-test-kit/src/tsconfig.json
  packages/e2e-test-kit/src/webpack-in-memory-test.ts
  packages/e2e-test-kit/test/index.spec.ts
  packages/e2e-test-kit/test/tsconfig.json
  packages/stylable-build-test-kit/README.md
  packages/stylable-cli/README.md
  packages/stylable-cli/package.json
  packages/stylable-cli/test/build.spec.ts
  packages/stylable-cli/test/generate-index.spec.ts
  packages/stylable-jest/README.md
  packages/stylable-node/README.md
  packages/stylable-runtime/README.md
  packages/stylable-scripts/README.md
  packages/stylable-webpack-extensions/README.md
  packages/stylable-webpack-extensions/test/e2e/html-snapshot-plugin-project.spec.ts
  packages/stylable-webpack-extensions/test/e2e/metadata-plugin-project.spec.ts
  packages/stylable-webpack-plugin/README.md
  packages/stylable-webpack-plugin/package.json
  packages/stylable-webpack-plugin/test/e2e/3rd-party.spec.ts
  packages/stylable-webpack-plugin/test/e2e/4th-party-project.spec.ts
  packages/stylable-webpack-plugin/test/e2e/autoprefixer-project.spec.ts
  packages/stylable-webpack-plugin/test/e2e/bad-project.spec.ts
  packages/stylable-webpack-plugin/test/e2e/dynamic-chunk-3dparty-split-project.spec.ts
  packages/stylable-webpack-plugin/test/e2e/dynamic-chunk-depth-project.spec.ts
  packages/stylable-webpack-plugin/test/e2e/hooked-project.spec.ts
  packages/stylable-webpack-plugin/test/e2e/library-project.spec.ts
  packages/stylable-webpack-plugin/test/e2e/mixins-project.spec.ts
  packages/stylable-webpack-plugin/test/e2e/optimizations.spec.ts
  packages/stylable-webpack-plugin/test/e2e/project-with-assets.spec.ts
  packages/stylable-webpack-plugin/test/e2e/raw-project.spec.ts
  packages/stylable-webpack-plugin/test/e2e/simple-production-project.spec.ts
  packages/stylable-webpack-plugin/test/e2e/simplest-project.spec.ts
  packages/stylable-webpack-plugin/test/e2e/split-chunks.spec.ts
  packages/stylable/README.md
Labels: docs, tech debt

#404 change runtime stylesheet path to be required instead of resolved to cjs
  packages/node/src/require-hook.ts
  packages/node/src/stylable-module-factory.ts
  packages/node/src/stylable-module-source.ts
  packages/webpack-plugin/test/e2e/dev-mode-warnings-project.spec.ts
Labels: integration, tech debt

#412 dom-test-kit: extract package from core testing utils
  README.md
  packages/cli/README.md
  packages/cli/package.json
  packages/core/README.md
  packages/core/tests/utils/test-utils.ts
  packages/dom-test-kit/LICENSE
  packages/dom-test-kit/README.md
  packages/dom-test-kit/package.json
  packages/dom-test-kit/src/index.ts
  packages/dom-test-kit/src/stylable-dom-util.ts
  packages/dom-test-kit/tests/stylable-dom-util.spec.ts
  packages/dom-test-kit/tsconfig.json
  packages/dom-test-kit/tslint.json
  packages/dom-test-kit/webpack.config.js
  packages/e2e-test-kit/README.md
  packages/e2e-test-kit/package.json
  packages/jest/README.md
  packages/jest/package.json
  packages/node/README.md
  packages/node/package.json
  packages/react-scripts/README.md
  packages/react-scripts/package.json
  packages/runtime/README.md
  packages/runtime/package.json
  packages/webpack-extensions/package.json
  packages/webpack-plugin/README.md
Labels: infrastructure, integration, tests

#413 Added a 'getLogicModule' option to the snapshot plugin
  packages/webpack-extensions/package.json
  packages/webpack-extensions/src/stylable-html-snapshot.ts
Labels: feature, integration

#407 Adding diagnostics
  packages/core/src/functions.ts
  packages/core/src/stylable-meta.ts
  packages/core/src/stylable-mixins.ts
  packages/core/src/stylable-processor.ts
  packages/core/src/stylable-resolver.ts
  packages/core/src/stylable-transformer.ts
  packages/core/tests/diagnostics.spec.ts
  packages/core/tests/functions.spec.ts
  packages/core/tests/mixins/mixins.spec.ts
  packages/core/tests/stylable-processor.spec.ts
  packages/core/tests/stylable-resolver.spec.ts
  packages/webpack-plugin/test/e2e/bad-project.spec.ts
Labels: core, diagnostics

#414 Add repository url to all package.json files
  packages/cli/package.json
  packages/core/package.json
  packages/dom-test-kit/package.json
  packages/e2e-test-kit/package.json
  packages/jest/package.json
  packages/node/package.json
  packages/react-scripts/package.json
  packages/runtime/package.json
  packages/stylable.io/package.json
  packages/webpack-extensions/package.json
  packages/webpack-plugin/package.json
Labels: infrastructure

#415 Add missing 'yargs' dependency to @stylable/cli
  packages/cli/package.json
Labels: bug, integration
