Repository wix/stylable, pull requests merged in 2019-07, with the labels that each got.

#688 Schema Extract: fixes and additions
  packages/runtime/README.md
  packages/runtime/test/unit/css-runtime-stylesheet-legacy.spec.ts
  packages/schema-extract/src/index.ts
  packages/schema-extract/src/main.ts
  packages/schema-extract/src/types.ts
  packages/schema-extract/test/test.spec.ts
Labels: integration, tech debt

#669 Add minify and optimize support in CLI
  packages/cli/README.md
  packages/cli/package.json
  packages/cli/src/build.ts
  packages/cli/src/cli.ts
  packages/cli/test/build.spec.ts
  packages/cli/test/generate-index.spec.ts
Labels: feature, integration

#692 stylable.io: add documentation for custom value variables
  packages/stylable.io/docs/references/variables.md
Labels: docs

#702 Replace current CSS minifier (CleanCSS) with CSSO
  package.json
  packages/optimizer/package.json
  packages/optimizer/src/stylable-optimizer.ts
  packages/webpack-plugin/test/e2e/optimizations.spec.ts
  yarn.lock
Labels: bug, infrastructure

#704 Add compat/minify modes to the CLI
  packages/cli/README.md
  packages/cli/src/build.ts
  packages/cli/src/cli.ts
  packages/cli/test/build.spec.ts
  packages/cli/test/cli.spec.ts
  packages/module-utils/src/module-source.ts
  packages/module-utils/test/test-kit.ts
Labels: tech debt, tooling

#705 Disable minifier restructuring in optimizer
  packages/optimizer/src/stylable-optimizer.ts
Labels: bug, integration

#707 [core, schema-extract] Add cssDocs support
  packages/core/package.json
  packages/core/src/cssdocs.ts
  packages/core/src/index.ts
  packages/core/src/stylable-meta.ts
  packages/core/src/stylable-processor.ts
  packages/core/src/stylable-transformer.ts
  packages/core/test/cssdocs.spec.ts
  packages/schema-extract/src/main.ts
  packages/schema-extract/src/types.ts
  packages/schema-extract/test/cssdocs.spec.ts
  packages/schema-extract/test/mock-namespace.ts
  packages/schema-extract/test/test.spec.ts
  yarn.lock
Labels: core, feature, tooling

#721 export default from legacy
  packages/module-utils/src/module-factory.ts
  packages/module-utils/test/index.spec.ts
Labels: bug, tech debt
