Repository wix/stylable, pull requests merged in 2020-05, with the labels that each got.

#1137 Language Service: ColorPresentation edits "value(x)" colors inline
  packages/core/src/cached-process-file.ts
  packages/language-service/src/lib/feature/color-provider.ts
  packages/language-service/src/lib/service.ts
  packages/language-service/test-kit/stylable-fixtures-lsp.ts
  packages/language-service/test/fixtures/server-cases/colors/imported-color.st.css
  packages/language-service/test/fixtures/server-cases/colors/substring-var-import.st.css
  packages/language-service/test/lib/colors.spec.ts
  packages/language-service/test/lib/diagnostics.spec.ts
Labels: API, language-service

#924 Add optional "noCollisionNamespace" namespace resolver
  package.json
  packages/core/src/index.ts
  packages/core/src/resolve-namespace-factories.ts
  packages/core/test/resolve-namespace-factories.spec.ts
  packages/node/package.json
  packages/node/src/resolve-namespace.ts
  yarn.lock
Labels: feature, integration

#1176 LSP: add document formatting providers
  package.json
  packages/language-service/package.json
  packages/language-service/src/index.ts
  packages/language-service/src/lib/feature/formatting.ts
  packages/language-service/src/lib/service.ts
  packages/language-service/test-kit/asserters.ts
  packages/language-service/test/lib/formatting.spec.ts
  yarn.lock
Labels: feature, language-service

#1184 Use generated namespace as unique identifier in optimizing cache keys
  packages/optimizer/src/namespace-optimizer.ts
Labels: bug, integration

#1173 Ignore modules with no stylable buildInfo
  packages/webpack-plugin/src/stylable-webpack-plugin.ts
  packages/webpack-plugin/test/e2e/watched-project.spec.ts
Labels: bug, integration

#1178 Metadata loader
  package.json
  packages/webpack-extensions/README.md
  packages/webpack-extensions/package.json
  packages/webpack-extensions/src/index.ts
  packages/webpack-extensions/src/stylable-metadata-loader.ts
  packages/webpack-extensions/test/e2e/metadata-loader-case.spec.ts
  packages/webpack-extensions/test/e2e/projects/metadata-loader-case/comp.st.css
  packages/webpack-extensions/test/e2e/projects/metadata-loader-case/globals.d.ts
  packages/webpack-extensions/test/e2e/projects/metadata-loader-case/index.st.css
  packages/webpack-extensions/test/e2e/projects/metadata-loader-case/index.ts
  packages/webpack-extensions/test/e2e/projects/metadata-loader-case/stylable.config.js
  packages/webpack-extensions/test/e2e/projects/metadata-loader-case/webpack.config.ts
  packages/webpack-plugin/src/is-loaded-by-loaders.ts
  packages/webpack-plugin/src/stylable-webpack-plugin.ts
  yarn.lock
Labels: integration, tooling
