Repository wix/stylable, pull requests merged in 2020-07, with the labels that each got.

#1241 Jest: added core path and version to Jest integration caching key
  packages/jest/src/jest.ts
Labels: integration

#1238 Experimental-loader: add exportsOnly mode for transform loader
  packages/experimental-loader/README.md
  packages/experimental-loader/src/create-runtime-target-code.ts
  packages/experimental-loader/src/stylable-runtime-loader.ts
  packages/experimental-loader/src/stylable-transform-loader.ts
  packages/experimental-loader/test/exports-only-mode.spec.ts
  packages/experimental-loader/test/projects/exports-only-mode/index.js
  packages/experimental-loader/test/projects/exports-only-mode/index.st.css
  packages/experimental-loader/test/projects/exports-only-mode/webpack.config.ts
Labels: integration

#1243 Barak/st scope annotation
  packages/core/src/stylable-processor.ts
  packages/core/test/scope-directive.spec.ts
Labels: core

#1256 Add support for content hash in webpack css output
  packages/webpack-plugin/src/hash-content-util.ts
  packages/webpack-plugin/src/stylable-webpack-plugin.ts
  packages/webpack-plugin/test/e2e/projects/simplest-project-content-hash/src/index.js
  packages/webpack-plugin/test/e2e/projects/simplest-project-content-hash/src/index.st.css
  packages/webpack-plugin/test/e2e/projects/simplest-project-content-hash/webpack.config.js
  packages/webpack-plugin/test/e2e/simplest-project-content-hash.spec.ts
Labels: bug, integration

#1261 Stylable manifest plugin
  packages/webpack-extensions/package.json
  packages/webpack-extensions/src/component-metadata-builder.ts
  packages/webpack-extensions/src/create-metadata-stylesheet.ts
  packages/webpack-extensions/src/stylable-manifest-plugin.ts
  packages/webpack-extensions/src/stylable-metadata-loader.ts
  packages/webpack-extensions/test/e2e/projects/manifest-plugin/Button.comp.st.css
  packages/webpack-extensions/test/e2e/projects/manifest-plugin/common.st.css
  packages/webpack-extensions/test/e2e/projects/manifest-plugin/index.ts
  packages/webpack-extensions/test/e2e/projects/manifest-plugin/manifest.spec.ts
  packages/webpack-extensions/test/e2e/projects/manifest-plugin/package.json
  packages/webpack-extensions/test/e2e/projects/manifest-plugin/webpack.config.ts
Labels: integration, tooling

#1260 add option to emit errors for error diagnostics
  packages/webpack-plugin/README.md
  packages/webpack-plugin/src/plugin-options.ts
  packages/webpack-plugin/src/stylable-generator.ts
  packages/webpack-plugin/src/types.ts
  packages/webpack-plugin/test/e2e/errors-project.spec.ts
  packages/webpack-plugin/test/e2e/projects/errors-project/src/index.js
  packages/webpack-plugin/test/e2e/projects/errors-project/src/index.st.css
  packages/webpack-plugin/test/e2e/projects/errors-project/src/test.st.css
  packages/webpack-plugin/test/e2e/projects/errors-project/webpack.config.js
Labels: integration

#1262 Experimental loader emit diagnostics as webpack errors and warnings
  packages/e2e-test-kit/src/project-runner.ts
  packages/experimental-loader/README.md
  packages/experimental-loader/src/stylable-transform-loader.ts
  packages/experimental-loader/test/errors-integration.spec.ts
  packages/experimental-loader/test/projects/errors-integration/index.js
  packages/experimental-loader/test/projects/errors-integration/index.st.css
  packages/experimental-loader/test/projects/errors-integration/webpack.config.ts
Labels: diagnostics, feature

#1259 Add new ESLint plugin for runtime Stylable usage
  packages/eslint-plugin-stylable/LICENSE
  packages/eslint-plugin-stylable/README.md
  packages/eslint-plugin-stylable/index.js
  packages/eslint-plugin-stylable/package.json
  packages/eslint-plugin-stylable/src/index.ts
  packages/eslint-plugin-stylable/src/stylable-es-lint.ts
  packages/eslint-plugin-stylable/src/webpack-resolve-schema.ts
  packages/eslint-plugin-stylable/tests/stylable-es-lint.spec.ts
  yarn.lock
Labels: diagnostics, tooling

#1266 Fix lint error on computed member identifier
  packages/eslint-plugin-stylable/src/stylable-es-lint.ts
  packages/eslint-plugin-stylable/tests/stylable-es-lint.spec.ts
Labels: bug, tooling

#1267 infra: use GitHub Actions
  .github/workflows/npm.yml
  .github/workflows/tests.yml
  .travis.yml
  README.md
Labels: infrastructure

#1265 Better Webpack diagnostics options & Add onProcessMeta hook
  packages/experimental-loader/src/stylable-transform-loader.ts
  packages/webpack-plugin/README.md
  packages/webpack-plugin/src/plugin-options.ts
  packages/webpack-plugin/src/stylable-generator.ts
  packages/webpack-plugin/src/stylable-webpack-plugin.ts
  packages/webpack-plugin/src/types.ts
  packages/webpack-plugin/test/e2e/projects/bad-project/webpack.config.js
  packages/webpack-plugin/test/e2e/projects/errors-project/webpack.config.js
Labels: diagnostics, integration, tech debt

#1283 Set "@stylable/runtime" build target to ES5
  .prettierignore
  packages/experimental-loader/src/create-runtime-target-code.ts
  packages/runtime/src/tsconfig.json
Labels: runtime

#1284 refactor: format output js a bit nicer
  packages/module-utils/src/module-source.ts
Labels: tech debt
