Repository wix/stylable, pull requests merged in 2021-08, with the labels that each got.

#1962 fix(core): assure that pseudo-classes warn when no arguments are given
  packages/core/src/pseudo-states.ts
  packages/core/test/pseudo-states.spec.ts
Labels: core, diagnostics

#1961 fix(language-service): improve definition support for both :import and @st-import
  packages/language-service/src/lib/provider.ts
  packages/language-service/test/fixtures/server-cases/definitions/imported-default.st.css
  packages/language-service/test/fixtures/server-cases/definitions/imported-path.st.css
  packages/language-service/test/fixtures/server-cases/definitions/st-imported-default.st.css
  packages/language-service/test/fixtures/server-cases/definitions/st-imported-named-end.st.css
  packages/language-service/test/fixtures/server-cases/definitions/st-imported-named-start.st.css
  packages/language-service/test/fixtures/server-cases/definitions/st-imported-path.st.css
  packages/language-service/test/lib/definitions.spec.ts
Labels: bug, language-service, tech debt

#1946 docs(core-test-kit): add missing mixin from example
  packages/core-test-kit/README.md
  packages/core-test-kit/src/matchers/results.ts
  packages/experimental-loader/README.md
Labels: docs, tests

#1933 fix(module-utils): locally extended states are now emitted in the generated .d.ts
  packages/module-utils/src/generate-dts-sourcemaps.ts
  packages/module-utils/src/generate-dts.ts
  packages/module-utils/test/generate-dts.spec.ts
  packages/module-utils/test/sourcemap.spec.ts
Labels: bug, tooling, types

#1973 feat(core): support defining and using global keyframes
  packages/core/src/stylable-meta.ts
  packages/core/src/stylable-processor.ts
  packages/core/src/stylable-transformer.ts
  packages/core/src/stylable-value-parsers.ts
  packages/core/src/utils.ts
  packages/core/test/diagnostics.spec.ts
  packages/core/test/stylable-processor.spec.ts
  packages/core/test/stylable-transformer/global.spec.ts
Labels: feature, core

#2011 fix(cli): add missing 'module-utils' dependency (v3)
  packages/cli/package.json
Labels: bug, tooling

#2018 feat(core): add CSS function notation syntax for "stMap" and "stArray"
  packages/build-tools/src/process-url-dependencies.ts
  packages/core/src/custom-values.ts
  packages/core/src/stylable-assets.ts
  packages/core/src/stylable-processor.ts
  packages/core/src/stylable-utils.ts
  packages/core/test/functions.spec.ts
  packages/core/test/stylable-transformer/exports.spec.ts
  packages/core/test/stylable-transformer/value.spec.ts
Labels: feature, core

#2027 chore: explicitly export instead of export all
  packages/build-tools/src/index.ts
  packages/cli/src/index.ts
  packages/code-formatter/src/index.ts
  packages/core-test-kit/src/index.ts
  packages/core/src/index.ts
  packages/create-stylable-app/src/index.ts
  packages/custom-value/src/index.ts
  packages/dom-test-kit/src/index.ts
  packages/e2e-test-kit/src/index.ts
  packages/jest/src/index.ts
  packages/language-service/src/index.ts
  packages/module-utils/src/index.ts
  packages/node/src/index.ts
  packages/optimizer/src/index.ts
  packages/runtime/src/index.ts
  packages/schema-extract/src/index.ts
  packages/uni-driver/src/index.ts
  packages/webpack-extensions/src/index.ts
  packages/webpack-plugin/src/index.ts
  typings/externals/index.d.ts
Labels: tech debt

#1693 feat(cli): add code-mod utility in CLI that refactors old ":import" to the new "@st-import"
  packages/cli/bin/stc-codemod.js
  packages/cli/package.json
  packages/cli/src/cli-codemod.ts
  packages/cli/src/code-mods/apply-code-mods.ts
  packages/cli/src/code-mods/code-mods.ts
  packages/cli/src/code-mods/st-import-to-at-import.ts
  packages/cli/test/cli-codemod.spec.ts
  packages/cli/test/test-kit/cli-test-kit.ts
  packages/core/src/index.ts
  packages/core/src/stylable-processor.ts
Labels: tooling
