Repository wix/stylable, pull requests merged in 2021-07, with the labels that each got.

#1905 infra(ci): enable cache in setup-node
  .github/workflows/npm.yml
  .github/workflows/release3.yml
  .github/workflows/tests.yml
Labels: infrastructure

#1904 feat(cli): allow generateReExports to filter files from index generation
  packages/cli/src/base-generator.ts
  packages/cli/test/fixtures/test-generator.ts
  packages/cli/test/generate-index.spec.ts
Labels: 3.x, tooling

#1902 feat(cli): allow generateReExports to filter files from index generation
  packages/cli/src/base-generator.ts
  packages/cli/test/fixtures/test-generator.ts
  packages/cli/test/generate-index.spec.ts
Labels: tooling

#1908 fix(core): emit validation diagnostics on @st-imports
  packages/core/src/stylable-resolver.ts
  packages/core/test/diagnostics.spec.ts
  packages/core/test/stylable-resolver.spec.ts
Labels: bug, core, diagnostics

#1919 fix(language-service): limit api break to type fix
  packages/language-service/src/lib/feature/formatting.ts
  packages/language-service/src/lib/service.ts
  packages/language-service/test/test-kit/asserters.ts
Labels: API, bug, language-service

#1924 fix(cli): watch did not copy changed assets referenced by Stylable files
  packages/cli/src/build.ts
  packages/cli/test/cli-watch.spec.ts
Labels: bug, infrastructure

#1912 refactor(core-test-kit): reduce semi-duplicate APIs
  .gitignore
  packages/core-test-kit/README.md
  packages/core-test-kit/src/diagnostics.ts
  packages/core-test-kit/src/generate-test-util.ts
  packages/core-test-kit/src/match-rules.ts
  packages/core/test/stylable-resolver.spec.ts
  packages/core/test/stylable-transformer/elements.spec.ts
  packages/optimizer/test/stylable-optimizer.spec.ts
Labels: tech debt, tests

#1874 feat(core): don't transform custom states to attributes
  packages/core/src/pseudo-states.ts
  packages/core/test/pseudo-states.spec.ts
  packages/dom-test-kit/src/stylable-dom-util.ts
  packages/webpack-extensions/test/unit/forcestates-plugin.spec.ts
Labels: core, pseudo-state

#1943 fix(code-formatter): api accidentaly public now private
  packages/code-formatter/src/formatter.ts
Labels: bug, tooling
