Repository wix/stylable, pull requests merged in 2021-11, with the labels that each got.

#2136 refactor: remove deprecation logs from matchSelectorTarget and createSubsetAst
  packages/core/src/index.ts
Labels: deprecated, API

#2128 refactor(core): extend resolver cache entity
  packages/core/src/index.ts
  packages/core/src/stylable-resolver.ts
  packages/rollup-plugin/test/projects/simple-stylable/index.st.css
Labels: tech debt

#2140 infra: limit the number of jobs in the test runner
  .mocharc.js
Labels: infrastructure

#2145 feat(core): export `parseStylableImport`
  packages/core/src/index.ts
  packages/core/src/stylable-imports-tools.ts
Labels: API

#2148 refactor: remove lerna dependency
  README.md
  package.json
  yarn.lock
Labels: tech debt

#2159 fix(jest): correct export to match Jest API expectation
  packages/jest/src/index.ts
  packages/jest/src/jest.ts
  packages/jest/test/jest.spec.ts
Labels: bug, integration

#2151 refactor!?: rewrite project runner startup process
  .gitignore
  .mocharc.js
  packages/e2e-test-kit/src/browser-server.ts
  packages/e2e-test-kit/src/isolated-server.ts
  packages/e2e-test-kit/src/project-runner.ts
  packages/e2e-test-kit/src/stylable-project-runner.ts
  packages/rollup-plugin/test/test-kit/rollup-runner.ts
  packages/webpack-extensions/test/e2e/fs-manifest.spec.ts
  packages/webpack-extensions/test/e2e/manifest.css-vars.spec.ts
  packages/webpack-extensions/test/e2e/manifest.spec.ts
  packages/webpack-extensions/test/e2e/metadata-loader-case.spec.ts
  packages/webpack-plugin/test/e2e/hd-cache.spec.ts
  packages/webpack-plugin/test/e2e/project-with-3rd-party-mixin-assets.spec.ts
  packages/webpack-plugin/test/e2e/project-with-assets.spec.ts
  packages/webpack-plugin/test/e2e/project-with-inline-assets.spec.ts
  packages/webpack-plugin/test/e2e/watched-project-error-recovery.spec.ts
  packages/webpack-plugin/test/e2e/watched-project.spec.ts
Labels: tests

#2150 feat(webpack-plugin): add more details to the duplicate namespace report
  packages/webpack-plugin/src/plugin-utils.ts
  packages/webpack-plugin/src/plugin.ts
  packages/webpack-plugin/test/e2e/duplicate-namespace.spec.ts
  packages/webpack-plugin/test/e2e/projects/duplicate-namespace/node_modules/lib1/index.js
  packages/webpack-plugin/test/e2e/projects/duplicate-namespace/node_modules/lib1/index.st.css
  packages/webpack-plugin/test/e2e/projects/duplicate-namespace/node_modules/lib1/package.json
  packages/webpack-plugin/test/e2e/projects/duplicate-namespace/node_modules/lib2/index.js
  packages/webpack-plugin/test/e2e/projects/duplicate-namespace/node_modules/lib2/index.st.css
  packages/webpack-plugin/test/e2e/projects/duplicate-namespace/node_modules/lib2/package.json
  packages/webpack-plugin/test/e2e/projects/duplicate-namespace/src/index.js
  packages/webpack-plugin/test/e2e/projects/duplicate-namespace/src/index.st.css
  packages/webpack-plugin/test/e2e/projects/duplicate-namespace/webpack.config.js
Labels: integration

#2168 fix(core): restrict functional nested selectors analyze
  packages/core/src/native-reserved-lists.ts
  packages/core/src/pseudo-states.ts
  packages/core/src/stylable-processor.ts
  packages/core/test/pseudo-states.spec.ts
  packages/core/test/stylable-processor.spec.ts
Labels: bug, core

#2135 fix!: unify resolvePath, always resolve request via resolver and remove resolve from fileProcessor
  packages/cli/src/build.ts
  packages/cli/test/cli-watch.spec.ts
  packages/cli/test/generate-index.spec.ts
  packages/cli/test/test-kit/cli-test-kit.ts
  packages/core-test-kit/src/generate-test-util.ts
  packages/core/package.json
  packages/core/src/cached-process-file.ts
  packages/core/src/create-infra-structure.ts
  packages/core/src/create-stylable-processor.ts
  packages/core/src/functions.ts
  packages/core/src/index.ts
  packages/core/src/module-resolver.ts
  packages/core/src/module-with-extensions.ts
  packages/core/src/stylable-mixins.ts
  packages/core/src/stylable-resolver.ts
  packages/core/src/stylable-transformer.ts
  packages/core/src/stylable.ts
  packages/core/src/timed-cache.ts
  packages/core/test/cached-process-file.spec.ts
  packages/core/test/stylable-resolver.spec.ts
  packages/core/test/timed-cache.spec.ts
  packages/eslint-plugin-stylable/src/stylable-es-lint.ts
  packages/language-service/src/lib/completion-providers.ts
  packages/language-service/src/lib/feature/color-provider.ts
  packages/language-service/src/lib/provider.ts
  packages/webpack-extensions/src/stylable-manifest-plugin.ts
  packages/webpack-extensions/src/stylable-metadata-loader.ts
  packages/webpack-plugin/src/plugin.ts
  webpack-config-browser/webpack.config.base.js
Labels: core, tech debt

#2174 infra: require browser-server only when it necessary in vscode launch
  .mocharc.js
  .vscode/launch.json
Labels: infrastructure
