Repository wix/stylable, pull requests merged in 2021-06, with the labels that each got.

#1844 Fix global type definition to set default export as unknown instead of never
  packages/create-stylable-app/template/ts-react-rollup/typings/globals.d.ts
  packages/create-stylable-app/template/ts-react-webpack/typings/globals.d.ts
  packages/runtime/README.md
Labels: bug, tooling

#1832 add error when nesting rules
  packages/core/src/stylable-processor.ts
  packages/core/test/stylable-processor.spec.ts
Labels: core, diagnostics

#1743 Add file watch service to CLI
  packages/cli/README.md
  packages/cli/package.json
  packages/cli/src/base-generator.ts
  packages/cli/src/build-single-file.ts
  packages/cli/src/build-tools.ts
  packages/cli/src/build.ts
  packages/cli/src/cli.ts
  packages/cli/src/directory-process-service/directory-process-service.ts
  packages/cli/src/directory-process-service/walk-fs.ts
  packages/cli/src/generate-manifest.ts
  packages/cli/src/handle-assets.ts
  packages/cli/src/index.ts
  packages/cli/src/logger.ts
  packages/cli/src/project-config.ts
  packages/cli/src/report-diagnostics.ts
  packages/cli/test/build.spec.ts
  packages/cli/test/cli-watch.spec.ts
  packages/cli/test/cli.spec.ts
  packages/cli/test/directory-process-service/directory-process-service.spec.ts
  packages/cli/test/generate-index.spec.ts
  packages/cli/test/test-kit/cli-test-kit.ts
  packages/node/src/find-files.ts
  packages/webpack-extensions/src/stylable-metadata-plugin.ts
Labels: feature, tech debt, tooling

#1859 Fix flaky CLI watch test to support stdout event grouping
  packages/cli/test/cli-watch.spec.ts
  packages/cli/test/test-kit/cli-test-kit.ts
Labels: bug, tests, tooling

#1766 Generate ".d.ts" definition files for Stylable stylesheets
  package.json
  packages/cli/README.md
  packages/cli/src/build-single-file.ts
  packages/cli/src/build.ts
  packages/cli/src/cli.ts
  packages/cli/test/build.spec.ts
  packages/cli/test/cli.spec.ts
  packages/dom-test-kit/src/stylable-dom-util.ts
  packages/dom-test-kit/test/stylable-dom-util.spec.ts
  packages/e2e-test-kit/src/dts-kit.ts
  packages/e2e-test-kit/src/index.ts
  packages/eslint-plugin-stylable/README.md
  packages/module-utils/package.json
  packages/module-utils/src/dts-rough-tokenizer.ts
  packages/module-utils/src/generate-dts-sourcemaps.ts
  packages/module-utils/src/generate-dts.ts
  packages/module-utils/src/index.ts
  packages/module-utils/src/module-source.ts
  packages/module-utils/test/dts-rough-tokenizer.spec.ts
  packages/module-utils/test/generate-dts.spec.ts
  packages/module-utils/test/sourcemap.spec.ts
  packages/module-utils/test/tsconfig.json
  yarn.lock
Labels: feature, tooling

#1875 test: enable parallel testing
  .github/workflows/tests.yml
  package.json
  packages/e2e-test-kit/src/project-runner.ts
  packages/experimental-loader/test/two-components-dynamic-order-prod.spec.ts
  packages/experimental-loader/test/two-components-dynamic-order.spec.ts
  packages/webpack-extensions/test/e2e/manifest.spec.ts
  packages/webpack-plugin/test/e2e/simplest-project.spec.ts
Labels: infrastructure, tests

#1877 Fix states runtime typings
  packages/runtime/src/runtime.ts
  packages/runtime/src/types.ts
Labels: bug, runtime, types

#1883 fix(webpack-plugin): mini-css-extract-plugin CSSModule build
  packages/webpack-plugin/src/mini-css-support.ts
  typings/externals/index.d.ts
Labels: bug, integration

#1893 fix: remove non es5 code from runtime stylesheet
  packages/runtime/src/runtime.ts
Labels: bug, runtime
