Repository wix/stylable, pull requests merged in 2021-12, with the labels that each got.

#2194 fix(core): fix regression in inherited mixin flow
  packages/core/src/stylable-mixins.ts
  packages/core/test/mixins/css-mixins.spec.ts
Labels: bug, core, mixin

#2193 refactor(core): st-import feature extraction
  packages/cli/src/code-mods/st-import-to-at-import.ts
  packages/cli/test/build.spec.ts
  packages/cli/test/codemods/st-import-to-at-import.spec.ts
  packages/core-test-kit/src/diagnostics.ts
  packages/core/src/custom-values.ts
  packages/core/src/features/css-class.ts
  packages/core/src/features/css-type.ts
  packages/core/src/features/diagnostics.ts
  packages/core/src/features/feature.ts
  packages/core/src/features/index.ts
  packages/core/src/features/st-global.ts
  packages/core/src/features/st-import.ts
  packages/core/src/features/st-symbol.ts
  packages/core/src/features/types.ts
  packages/core/src/functions.ts
  packages/core/src/helpers/import.ts
  packages/core/src/helpers/value.ts
  packages/core/src/index.ts
  packages/core/src/pseudo-states.ts
  packages/core/src/stylable-meta.ts
  packages/core/src/stylable-processor.ts
  packages/core/src/stylable-resolver.ts
  packages/core/src/stylable-transformer.ts
  packages/core/src/stylable-value-parsers.ts
  packages/core/src/visit-meta-css-dependencies.ts
  packages/core/test/css-vars.spec.ts
  packages/core/test/diagnostics.spec.ts
  packages/core/test/features/css-class.spec.ts
  packages/core/test/features/css-type.spec.ts
  packages/core/test/features/st-import.spec.ts
  packages/core/test/helpers/import.spec.ts
  packages/core/test/scope-directive.spec.ts
  packages/core/test/st-import.spec.ts
  packages/core/test/stylable-import-tools.spec.ts
  packages/core/test/stylable-processor.spec.ts
  packages/core/test/stylable-transformer/general.spec.ts
  packages/core/test/stylable-value-parsers.spec.ts
  packages/language-service/src/lib/completion-providers.ts
  packages/rollup-plugin/src/index.ts
  packages/webpack-extensions/src/create-metadata-stylesheet.ts
  packages/webpack-plugin/src/loader-utils.ts
Labels: tech debt

#2211 fix: runtime readme
  packages/runtime/README.md
Labels: docs, runtime

#2203 feat: STSymbol setup to manage all symbols
  package-lock.json
  package.json
  packages/cli/test/cli.spec.ts
  packages/core/src/features/css-class.ts
  packages/core/src/features/css-type.ts
  packages/core/src/features/st-symbol.ts
  packages/core/src/stylable-mixins.ts
  packages/core/src/stylable-processor.ts
  packages/core/test/diagnostics.spec.ts
  packages/core/test/features/css-class.spec.ts
  packages/core/test/features/css-type.spec.ts
  packages/core/test/features/st-import.spec.ts
  packages/core/test/features/st-symbol.spec.ts
  packages/language-service/src/lib/completion-providers.ts
Labels: bug, tech debt

#2201 feat(webpack-plugin): add ability to report DUPLICATE_MODULE_NAMESPACE as warning
  packages/webpack-plugin/src/plugin-utils.ts
  packages/webpack-plugin/src/plugin.ts
  packages/webpack-plugin/test/e2e/duplicate-namespace-warning.spec.ts
  packages/webpack-plugin/test/e2e/projects/duplicate-namespace-warning/src/index.js
  packages/webpack-plugin/test/e2e/projects/duplicate-namespace-warning/src/index.st.css
  packages/webpack-plugin/test/e2e/projects/duplicate-namespace-warning/src/same-index.st.css
  packages/webpack-plugin/test/e2e/projects/duplicate-namespace-warning/webpack.config.js
Labels: diagnostics, integration

#2222 docs(webpack-plugin): add FAQ section
  packages/webpack-plugin/README.md
Labels: docs

#2230 fix(language-service): stylable completions should be sorted above css completions
  packages/language-service/src/lib/service.ts
  packages/language-service/test/lib/completions/completion.spec.ts
  packages/language-service/test/test-kit/asserters.ts
  packages/language-service/test/test-kit/stylable-in-memory-lsp.ts
Labels: bug, language-service

#2237 fix(code-formatter): grid formatting was breaking the css
  packages/code-formatter/src/formatter.ts
  packages/code-formatter/test/formatter.spec.ts
Labels: bug
