Repository wix/stylable, pull requests merged in 2022-12, with the labels that each got.

#2790 feat(core-test-kit): log diagnostics dump on diagnostic match fail
  packages/core-test-kit/src/inline-expectation.ts
  packages/core-test-kit/test/inline-expectations.spec.ts
Labels: tests, dev velocity

#2788 fix(language-service): st-global in at-rules definition
  packages/language-service/src/lib/css-service.ts
  packages/language-service/test/lib/completions/custom-property.spec.ts
  packages/language-service/test/lib/completions/keyframes.spec.ts
  packages/language-service/test/lib/completions/layer.spec.ts
Labels: bug, language-service

#2794 fix(webpack): preserve native CSS class names in production
  packages/webpack-plugin/src/loader.ts
  packages/webpack-plugin/src/plugin.ts
  packages/webpack-plugin/src/types.ts
  packages/webpack-plugin/test/e2e/native-css.spec.ts
  packages/webpack-plugin/test/e2e/projects/native-css/src/index.js
  packages/webpack-plugin/test/e2e/projects/native-css/src/local.css
Labels: bug, integration

#2780 feat: custom state with parameter to template
  packages/core/src/features/st-custom-state.ts
  packages/core/src/helpers/custom-state.ts
  packages/core/src/index-internal.ts
  packages/core/test/features/css-pseudo-class.spec.ts
  packages/core/test/features/st-custom-state.spec.ts
  packages/language-service/src/lib/completion-providers.ts
  packages/language-service/src/lib/feature/pseudo-class.ts
  packages/language-service/src/lib/provider.ts
  packages/language-service/test/fixtures/server-cases/states/with-param/comp-to-import-with-param-and-validators.st.css
  packages/language-service/test/fixtures/server-cases/states/with-param/enum/imported-state-with-template-enum-middle.st.css
  packages/language-service/test/fixtures/server-cases/states/with-param/enum/state-with-enum.st.css
  packages/language-service/test/fixtures/server-cases/states/with-param/imported-template-state-param-and-validators-suggestion.st.css
  packages/language-service/test/lib/completions/states.spec.ts
  packages/language-service/test/lib/signatures.spec.ts
  packages/module-utils/src/generate-dts.ts
  packages/module-utils/test/generate-dts.spec.ts
  packages/schema-extract/src/main.ts
  packages/schema-extract/src/types.ts
  packages/schema-extract/test/test.spec.ts
Labels: feature, core

#2783 fix: webpack optimization bailout for generate stylable modules
  packages/webpack-plugin/src/plugin-utils.ts
  packages/webpack-plugin/src/plugin.ts
  packages/webpack-plugin/src/webpack-entities.ts
Labels: bug, integration, tech debt

#2628 fix(cli): resolve namespaceResolver path relative to rootDir
  packages/cli/src/cli.ts
  packages/cli/test/cli.spec.ts
Labels: bug, tooling

#2798 feat: remove stylable directives at transform
  packages/cli/src/build-single-file.ts
  packages/core/src/stylable-transformer.ts
  packages/core/src/types.ts
  packages/core/test/features/css-class.spec.ts
  packages/core/test/features/css-pseudo-class.spec.ts
  packages/core/test/features/st-mixin.spec.ts
  packages/experimental-loader/package.json
  packages/experimental-loader/src/stylable-transform-loader.ts
  packages/optimizer/src/stylable-optimizer.ts
  packages/optimizer/test/stylable-optimizer.spec.ts
  packages/webpack-plugin/README.md
  packages/webpack-plugin/src/plugin.ts
  packages/webpack-plugin/test/e2e/optimizations.spec.ts
  packages/webpack-plugin/test/e2e/projects/optimizations/webpack.config.js
Labels: feature, tech debt

#2799 chore: replace deindent dependency
  package-lock.json
  package.json
  packages/code-formatter/test/formatter.spec.ts
  packages/code-formatter/test/tsconfig.json
  packages/core-test-kit/src/deindent.ts
  packages/core-test-kit/src/diagnostics.ts
  packages/core-test-kit/src/index.ts
  packages/core-test-kit/test/deindent.spec.ts
  packages/core/package.json
  packages/core/test/features/css-contains.spec.ts
  packages/core/test/features/css-custom-property.spec.ts
  packages/core/test/features/css-keyframes.spec.ts
  packages/core/test/features/css-layer.spec.ts
  packages/core/test/helpers/ast.spec.ts
  packages/core/test/stylable.spec.ts
  packages/language-service/test/lib/completions/contains.spec.ts
  packages/language-service/test/lib/completions/custom-property.spec.ts
  packages/language-service/test/lib/completions/keyframes.spec.ts
  packages/language-service/test/lib/completions/layer.spec.ts
  packages/language-service/test/lib/completions/namespace-directive.spec.ts
  packages/language-service/test/lib/diagnostics.spec.ts
  packages/language-service/test/tsconfig.json
  packages/module-utils/test/sourcemap.spec.ts
  packages/rollup-plugin/test/rollup-side-effects.spec.ts
  packages/rollup-plugin/test/tsconfig.json
Labels: tests, tech debt
