Repository wix/stylable, pull requests merged in 2023-01, with the labels that each got.

#2802 Fix `@stylable/core/src/types` import in public API
  packages/cli/src/config/projects-config.ts
  packages/core/src/index-internal.ts
Labels: bug, types

#2803 infra: enforce allowed import paths between packages
  .eslintrc
  packages/build-tools/src/process-url-dependencies.ts
  packages/cli/src/base-generator.ts
  packages/cli/src/code-mods/namespace-to-st-namespace.ts
  packages/cli/src/code-mods/st-global-custom-property-to-at-property.ts
  packages/cli/src/code-mods/st-import-to-at-import.ts
  packages/core/src/index-internal.ts
  packages/module-utils/src/generate-dts-sourcemaps.ts
  packages/runtime/src/index-internal.ts
  packages/schema-extract/src/cssdocs.ts
  packages/webpack-extensions/src/stylable-manifest-plugin.ts
  packages/webpack-plugin/src/webpack-entities.ts
Labels: infrastructure

#2806 chore: remove express dependency
  package-lock.json
  package.json
  packages/core/package.json
  packages/dom-test-kit/package.json
  packages/e2e-test-kit/package.json
  packages/e2e-test-kit/src/isolated-server.ts
  packages/optimizer/package.json
  packages/uni-driver/package.json
Labels: dependencies

#2268 feat(code-formatter): Implement new code formatter
  package-lock.json
  packages/cli/README.md
  packages/cli/src/code-format.ts
  packages/cli/test/code-format-cli.spec.ts
  packages/code-formatter/package.json
  packages/code-formatter/src/format-css.ts
  packages/code-formatter/src/formatter.ts
  packages/code-formatter/src/index.ts
  packages/code-formatter/test/formatter-experimental.spec.ts
  packages/language-service/src/lib/feature/formatting.ts
  packages/language-service/src/lib/service.ts
  packages/language-service/test/lib/formatting.spec.ts
  packages/language-service/test/test-kit/asserters.ts
Labels: tooling

#2810 infra(cli): clear cli test timeout that hold process
  packages/e2e-test-kit/src/cli-test-kit.ts
Labels: tests, dev velocity

#2808 feat(webpack): experimental flag for next 13 app directory
  packages/webpack-plugin/src/plugin.ts
Labels: bug, integration

#2815 fix(core): run collect imports deep only on stylable files
  packages/core/src/helpers/import.ts
Labels: core
