Repository wix/stylable, pull requests merged in 2023-11, with the labels that each got.

#2914 refactor!: unify runtime again
  package-lock.json
  packages/cli/src/build.ts
  packages/cli/test/build.spec.ts
  packages/core/src/stylable-js-module-source.ts
  packages/dom-test-kit/test/contract-test.ts
  packages/e2e-test-kit/src/stylable-webpack-test-utils.ts
  packages/esbuild/src/stylable-esbuild-plugin.ts
  packages/experimental-loader/src/create-runtime-target-code.ts
  packages/module-utils/test/test-kit.ts
  packages/node/src/loader.ts
  packages/rollup-plugin/runtime.js
  packages/rollup-plugin/src/index.ts
  packages/rollup-plugin/src/plugin-utils.ts
  packages/runtime/package.json
  packages/runtime/src/cached-node-renderer.ts
  packages/runtime/src/css-runtime-renderer.ts
  packages/runtime/src/css-runtime-stylesheet.ts
  packages/runtime/src/index-internal.ts
  packages/runtime/src/index.ts
  packages/runtime/src/inject-styles.ts
  packages/runtime/src/keyed-list-renderer.ts
  packages/runtime/src/pure.ts
  packages/runtime/src/runtime.ts
  packages/runtime/src/tsconfig.esm.json
  packages/runtime/src/types.ts
  packages/runtime/stylesheet.d.ts
  packages/runtime/test/unit/css-runtime-renderer.spec.ts
  packages/runtime/test/unit/css-runtime-stylesheet.spec.ts
  packages/runtime/test/unit/keyed-list-renderer.spec.ts
  packages/runtime/test/unit/micro-document.ts
  packages/runtime/test/unit/runtime.spec.ts
  packages/uni-driver/test/tsconfig.json
  packages/webpack-plugin/src/loader-utils.ts
  packages/webpack-plugin/src/loader.ts
  packages/webpack-plugin/src/plugin.ts
  packages/webpack-plugin/src/types.ts
  packages/webpack-plugin/src/webpack-entities.ts
  packages/webpack-plugin/test/e2e/dynamic-bug.spec.ts
  packages/webpack-plugin/test/e2e/dynamic-chunk-3rd-party-split-project.spec.ts
  packages/webpack-plugin/test/e2e/projects/dynamic-bug/webpack.config.js
  packages/webpack-plugin/test/e2e/projects/dynamic-chunk-3rd-party-split-project/src/index.js
  packages/webpack-plugin/test/e2e/projects/runtime-var-override-project/src/index.js
  packages/webpack-plugin/test/e2e/projects/runtime-var-override-project/src/index.st.css
  packages/webpack-plugin/test/e2e/projects/runtime-var-override-project/webpack.config.js
  packages/webpack-plugin/test/e2e/runtime-var-override-project.spec.ts
  scripts/build.js
Labels: tech debt, runtime

#2924 fix(runtime): expose stylesheet types in package exports
  packages/runtime/package.json
Labels: bug, integration

#2925 fix(core): scope nested global selector issues
  packages/core/src/helpers/selector.ts
  packages/core/test/features/css-class.spec.ts
  packages/core/test/features/st-mixin.spec.ts
Labels: bug, core

#2923 fix(cli): resolveNamespace cli arg should override stylable.config
  packages/cli/src/build-stylable.ts
  packages/cli/src/cli.ts
  packages/cli/src/config/resolve-options.ts
  packages/cli/src/types.ts
  packages/cli/test/cli.spec.ts
Labels: bug, tooling

#2926 feat(cli): accept resolveModule in buildStylable
  packages/cli/src/build-stylable.ts
Labels: feature, API
